[build]
  bin = "./bin/user-api"
  cmd = "go build -o ./bin/ ./cmd/user-api/"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
