version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: user_api_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5460:5432'
