version: '3.9'

services:

  user-api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - monitoring_network
    env_file:
      - ../.env
    container_name: user-api

networks:
  monitoring_network:
    external: true
